type Post{
		id:ID!
		body: String!
		createdAt: Timestamp!
		user: User!
		comments: [Comment]!
		likes: [Like]!
		likeCount: Int!
		commentCount: Int!
}

 type Query{
       getPosts: [Post] 
       getPost(id: ID!): Post
}

type Mutation{
	createPost(input: CreatePostInput): Post @auth
	deletePost(id: ID!): Boolean! @auth
}

input CreatePostInput{
	body: String! 
}