type Query{
    users: [User]
}

type Mutation{
    register(input: RegisterInput!): User!
    login(email: Email!, password: String!): User!
}

type User{
    id: ID!
    email: String!
    token: String!
    username: String! 
    createdAt: Timestamp!
}

input RegisterInput{
    username: String! 
    password: String!  
    retypePassword: String!
    email: Email! 
}